on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            # Install dependencies
            - name: Install Dependencies
              run: npm install

            # Run ESLint: this needs a eslint.config.(js|mjs|cjs) file
            - name: Run ESLint
              run: npx eslint . --ext .js,.jsx,.ts,.tsx

            # Run Prettier
            - name: Run Prettier Check
              run: npx prettier --check .