name: Lint Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies, including ESLint and Airbnb config
      - name: Install dependencies
        run: |
          npm install

      # Run ESLint to check for style and linting issues
      - name: Run ESLint on src/ only
        run: |
          npx eslint src/ --fix
          echo "ESLint on src/ completed successfully"

      # Output lint score based on the number of errors/warnings
